Add brief overview to readme
SciTools-incubator/iris-esmf-regrid pull request #152
Opened 2022-02-22 14:00 UTC by stephenworsley

Add enough documentation to the readme so that new users should be able to make use of the most important features by following the example.

2022-02-22 15:10 UTC, trexfeathers requested changes
Thanks @stephenworsley, this does a good job of getting the point across. But we can make it shorter/easier; that's what I've seen when looking at other repos that rely on their `README` as the ice-breaker:

* https://github.com/actions/cache
* https://github.com/SciTools/cf-units

2022-02-22 15:10 UTC, trexfeathers commented on README.md
> +`MeshToGridESMFRegridder` and `GridToMeshESMFRegridder`). We can do this as follows:
Don't bother listing which ones, you'll only have to change later.

2022-02-22 15:10 UTC, trexfeathers commented on README.md
> +
I feel like we could get the same point across with half the characters. This is the first thing people see, let's make it snappy 😁

2022-02-22 18:47 UTC, trexfeathers commented
Already looking loads better IMO 🙂

2022-02-23 10:39 UTC, zklaus commented
I think the main path to regridding should still follow the standard approach in Iris for regridding as documented [here](https://scitools-iris.readthedocs.io/en/latest/userguide/interpolation_and_regridding.html#regridding), don't you think?

As such, the first and principal example should be something along the lines of
```
result = source_cube.regrid(target_cube, esmf_regrid.ESMFRegrid())
```

2022-02-23 11:12 UTC, stephenworsley commented
@zklaus Ultimately, I think the documentation probably would benefit from looking more like the iris documentation. With that said, the current implementation of regridders does not go so far as to offer an exact match to iris functionality. This documentation reflects that and describes the regridding functionality which is common between the structured and unstructured regridders. The cached regridder is also necessary to introduce to discus regridder saving, which is a new feature not contained in iris. The unstructured and structured regridders are currently a little disjointed in their functionality and I hope to be unify them in a future release, however now that UGRID support in iris has released, I'm keen to release what we have for unstructured regridding as soon as possible, even if the structured and unstructured regridders do not yet have the same level of functionality.

2022-02-23 12:17 UTC, trexfeathers approved these changes

2022-02-23 12:17 UTC, merged