Allow regridding for projections in non-degree type units
SciTools-incubator/iris-esmf-regrid pull request #178
Opened 2022-05-04 11:51 UTC by stephenworsley

Some projections, like OSGB, have units which cannot be converted to degrees (i.e. meters) and cause regridding to fail. This PR assumes that where a coordinate system exists, units ought to already be compatible with it.

2022-05-04 12:05 UTC, trexfeathers commented
Using [`pyproj.Proj`](https://pyproj4.github.io/pyproj/stable/api/proj.html) could be an easy way of converting these cases to degrees.

2022-05-05 12:51 UTC, stephenworsley commented
> Using [`pyproj.Proj`](https://pyproj4.github.io/pyproj/stable/api/proj.html) could be an easy way of converting these cases to degrees.

This conversion ought to happen at this point:
https://github.com/SciTools-incubator/iris-esmf-regrid/blob/eca3a2a0dc4d5a2e8a2c8ae8535127f719d5fa4c/esmf_regrid/_esmf_sdo.py#L224-L225

I would imagine that cartopy would be calling Proj here anyway. I think that in the case where units are supplied in meters, at this point cartopy describes the projection as being described in meters and is expecting data to be in meters. There is still a case that there could be more to be done to ensure that units are compatible with the coordinate system, but I'm not sure what it would mean for a coordinate to have a unit which disagreed with the coordinate system. 

The approach I've gone for is to treat the coordinate system as the single source of truth for a coordinate where it exists. This seems the simplest way to do things for the time being.

2022-05-05 15:35 UTC, lbdreyer commented
Do you plan to add some testing to this PR?

2022-05-05 16:12 UTC, stephenworsley commented
> Do you plan to add some testing to this PR?

Yes, I have been thinking about adding tests. I think I would ideally want some OSGB data (or a subset of such data) to work with, since thats where this problem showed up. The closest I can find in iris-test-data seems to be transverse mercator (which i think OSGB is an instance of). If you have any other ideas of data to test this on let me know.

2023-10-11 13:11 UTC, trexfeathers requested changes
Thanks @stephenworsley, a few comments for you

2023-10-11 13:11 UTC, trexfeathers commented on esmf_regrid/tests/unit/schemes/test_ESMFAreaWeighted.py
> +    _test_non_degree_crs(ESMFAreaWeighted, expected_sum, expected_unmasked)
This is certainly a difficult one to get right, but to make the code more understandable I think both the setup and expected results need to be in the same place. So either:

- Contain the expected results within `_test_non_degree_crs()`, obviously as some sort of tuple given the various schemes.
- Generate the source and target in the function here, and pass those down to `_test_non_degree_crs()` as more arguments.

2023-10-26 16:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SciTools-incubator/iris-esmf-regrid?pullRequest=178) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SciTools-incubator/iris-esmf-regrid?pullRequest=178) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SciTools-incubator/iris-esmf-regrid?pullRequest=178) it.</sub>

2023-11-01 14:02 UTC, trexfeathers approved these changes

2023-11-01 14:02 UTC, trexfeathers commented
Thanks @stephenworsley!

2023-11-01 14:02 UTC, merged