Move benchmark code from nox to bm_runner
SciTools-incubator/iris-esmf-regrid pull request #361
Opened 2024-05-09 08:28 UTC by stephenworsley

Closes #281

2024-05-16 16:02 UTC, pp-mo requested changes
I've checked out the function of this now, and I'm happy it does function and contain what we need.
Just a few irrelevant references to fix I think (since you already ditched the unwanted Cperf code)

However, getting to grips with this has made me quite concerned about the future relationship of all this to the Iris benchmarking code, which it is similar to but significantly different.
 - for instance, I'm pleased that we didn't change noxfile.py here, but I'm pretty concerned at how that relates to the Iris code : a lot in common but multiple significant differences
  - on the other hand, the change here to asv_delegated_conda.py just keeps it exactly the same as in Iris, so that is easy to track + could be done with simple "templating" as [recently introduced into scitools/.github](https://github.com/SciTools/.github/pull/23).
The task of generalising so these two implementations can "share and differ as required" seems attractive but is clearly already non-trivial.  So, I'm hoping we can come up with better ways to do this in future, but **_not now_** !

2024-05-17 15:36 UTC, stephenworsley commented on benchmarks/bm_runner.py
> +class _CSPerf(_SubParserGenerator, ABC):
I was aiming for similarity with the iris structure where possible, though I agree that it doesn't make much sense in tis instance.

2024-05-20 14:41 UTC, pp-mo requested changes
Unfortunately I spotted a couple more problems which I think need fixing.
I did check local operation, and it does work :+1:

2024-05-20 15:14 UTC, pp-mo approved these changes

2024-05-20 15:15 UTC, pp-mo commented
Great stuff @stephenworsley -- thanks for your patience !

2024-05-20 15:15 UTC, merged